### ISSUE TITLE
data.sql 초기 데이터 입력 시 이슈

### ISSUE THREAD

**Issue by SeokRae** [spring-org/restful-web-service#14]
스프링 부트 버전이 2.5 이상부터 data.sql 적용하는 방법이 변경되어 
properties 설정 추가
https://springhow.com/spring-boot-version/

```properties
spring.jpa.defer-datasource-initialization=true
```

현재 프로퍼티 설정 정보

```yml
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
```
